version: 1.0.{build}
branches:
  only:
  - main
image: Visual Studio 2019
skip_tags: true
environment:
  CHOCOLATEY_API_KEY:
    secure: ii++/bG3kImf27812Cdx1P7qlzMiBrlnNm9KkG4V5YIrgfQ/mnw6iLxK4+J1+ZjA
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: false
  include_nuget_references: false
  publish_core_console: false
  verbosity: minimal
after_build:
- ps: >-
    dotnet publish --configuration Release

    Compress-Archive -Path src\bin\Release\net48\publish\ -DestinationPath .\SynchroFeed.Console-$env:APPVEYOR_BUILD_VERSION.zip

    $archiveHash = Get-FileHash -Path .\SynchroFeed.Console-$env:APPVEYOR_BUILD_VERSION.zip

    (((Get-Content -path .\legal\VERIFICATION-template.txt -Raw) -replace '{ArchiveHash}',$archiveHash.Hash)) -replace '{PackageVersion}', $env:APPVEYOR_BUILD_VERSION | Set-Content -Path .\legal\VERIFICATION.txt

    choco pack --version $env:APPVEYOR_BUILD_VERSION
artifacts:
- path: '*.zip'
- path: '*.nupkg'